[package]
name = "rust_tests"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["dylib"]

[dependencies]
tests_api.workspace = true
std_stuff.workspace = true

slotmap.workspace = true
hashbrown.workspace = true
slab.workspace = true
# stats_alloc.workspace = true